dependencies:
  build:
   - maven:3.5.4
   - java:8.252.09
   
build_targets:
  - name: default
    container:
      image: yourbase/yb_ubuntu:18.04
    commands:
      - mvn verify

ci:
  builds:
    - name: default
      build_target: default
